### PR TITLE
fixing-a-bug. adding placeholder image. fixes #7

### LINKED ISSUE #7: #INC-5312: Missing image
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

### PR DESCRIPTION
**Pull request by itays**
# Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### CODE REVIEW

**Comment by vanessa-cooper** [comment]
Thanks @itays, I'll review the changes right away!

**Comment by itays** [comment]
Screen Shot 2022-09-03 at 19 14 59

**Review by vanessa-cooper — CHANGES_REQUESTED** [review]
Make sure all checks pass, only then you can merge the PR.

**Review by vanessa-cooper — APPROVED** [review]
Excellent job @itays! You're now able to merge the PR.

**Pull request merged**
